version: '3'
services:
  database:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}' # изменить пароль для подключения
      - 'POSTGRES_USER=${POSTGRES_USER}' # изменить пользователя
    # При проксировании можно не открывать порты
    # ports:
    #   - '5438:5432' #порт для отладки и подключения
    networks:
      - web-service-network

  frontend:
    build:
      context: ./client
    ports:
    # Проксирование порта 80 на порт приложения 3000
      - "80:3000" # Указываем 80 порт - стандарт для протокола http
    networks:
      - web-service-network
    depends_on:
      - backend
    environment:
    - BASE_URL=${BACKEND_API_URL}

  backend:
    build:
      context: ./server
    ports:
      - "3001:3001" # Открыт для локального тестирования
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=database          # Ссылка на имя контейнера базы данных
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
    networks:
      - web-service-network
    depends_on:
      - database

networks:
  web-service-network:
    driver: bridge
